//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/fobler (inputer)/syvyys.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Syvyys: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Syvyys()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""syvyys"",
    ""maps"": [
        {
            ""name"": ""victim"",
            ""id"": ""8aca625b-1cf9-4877-a09d-5b4d3b1f00cb"",
            ""actions"": [
                {
                    ""name"": ""spin"",
                    ""type"": ""Value"",
                    ""id"": ""0c510d83-0672-42bf-90c5-e93d03c1efc0"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""af542900-a88b-4606-bd03-92a089653990"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""spin"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""be6005e1-9d3e-4d78-9adb-68a841082514"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""spin"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1cf49d62-18da-47a0-acc4-be86db4e185b"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""spin"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""86dc2ef2-164e-49b2-942f-045dc5588ffd"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""spin"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""fccbaffb-8958-4e51-9885-69fa2888f059"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""spin"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // victim
        m_victim = asset.FindActionMap("victim", throwIfNotFound: true);
        m_victim_spin = m_victim.FindAction("spin", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // victim
    private readonly InputActionMap m_victim;
    private List<IVictimActions> m_VictimActionsCallbackInterfaces = new List<IVictimActions>();
    private readonly InputAction m_victim_spin;
    public struct VictimActions
    {
        private @Syvyys m_Wrapper;
        public VictimActions(@Syvyys wrapper) { m_Wrapper = wrapper; }
        public InputAction @spin => m_Wrapper.m_victim_spin;
        public InputActionMap Get() { return m_Wrapper.m_victim; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(VictimActions set) { return set.Get(); }
        public void AddCallbacks(IVictimActions instance)
        {
            if (instance == null || m_Wrapper.m_VictimActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_VictimActionsCallbackInterfaces.Add(instance);
            @spin.started += instance.OnSpin;
            @spin.performed += instance.OnSpin;
            @spin.canceled += instance.OnSpin;
        }

        private void UnregisterCallbacks(IVictimActions instance)
        {
            @spin.started -= instance.OnSpin;
            @spin.performed -= instance.OnSpin;
            @spin.canceled -= instance.OnSpin;
        }

        public void RemoveCallbacks(IVictimActions instance)
        {
            if (m_Wrapper.m_VictimActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IVictimActions instance)
        {
            foreach (var item in m_Wrapper.m_VictimActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_VictimActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public VictimActions @victim => new VictimActions(this);
    public interface IVictimActions
    {
        void OnSpin(InputAction.CallbackContext context);
    }
}
